on:
  push:
    branches: [main]
  workflow_dispatch:
  jobs:
  generate-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      steps:
      - uses: actions/checkout@v4
      - name: Github Tag Bump
        id: tab_bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 1.0.2
          DEFAULT_BUMP: patch
        outputs:
          new_version: ${{ steps.tab_bump.outputs.new_tag }}
